apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: flask-api
  labels:
    app: taskmaster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi