apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: flask-api
  labels:
    app: taskmaster
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db